version: '3.8'

services:
  raj-portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2009:3000"  # Map container port 3000 to host port 2009
    environment:
      - NODE_ENV=production
    restart: unless-stopped 